### ISSUE TITLE
only 40 movies in list

### ISSUE THREAD

**Issue by georgew21** [jaruba/stremio-imdb-watchlist#1]
Hello, 

Unfortunately, this add-on adds only approximately 40 movies from my watchlist, although I have over 200.
Is there any way to add the full list?

Secondly, is this possible to add, also, the genres of the films ?

**Comment by jaruba** [comment]
I think ur right, it only parses the first 2 watchlist pages. I'll look into adding skipping functionality.

I know i can filter the results by: list_order, popularity, alphabetical, rating, votes, released, date_added. It's currently using date_added, so i can at least make filters for the other sorting options, did not check genre selection though, it might be possible, I'll look into it and tell u more as i research it.

**Comment by georgew21** [comment]
Thanks for the interesting to improve this useuful addon.

About the genres, in stremio discover page, when we view the movies from your addon in android, there is an option "all genres", tapping that, there is ability to _filter_ the movies by a specific genre. In pc there is this option,too

Your add-on doesn't add the meta info of the movies' genre, so we can't filter the movies based on the genre.

In general, in stremio this is the meta-info that stremio accepts: 

`"type": "movie", "id": "tt0032138", "name": "The Wizard of Oz", "poster": "https://images.metahub.space/poster/medium/tt0032138/img", "genres": ["Adventure", "Family", "Fantasy", "Musical"] `

So, if you could grab from imdb, the genres of movies, then it could be possible to filter (if we want) a specific and different each time genre of the watchlist in stremio.

thanks a lot.

**Comment by jaruba** [comment]
i know how to add filters to catalogs, but it doesn't work like that, if i send genres or not back with the meta items, Stremio doesn't automatically create the filters for them. I need to designate the filters (genres in this case) in the add-on itself and handle genre requests separately.

What i meant about researching it was that i need to check if i have a filter for playlists on the imdb site, which is where this data needs to ultimately come from.

**Comment by jaruba** [comment]
Ok, I think I added everything you requested, you should uninstall the old add-on, and install it from:

`https://imdb-watchlist.now.sh/ur1000000/manifest.json`

(replacing `ur1000000` with your IMDB user ID)

This adds catalog skipping, so you should be able to see your entire list of items. It also adds filtering by genre as you requested.

As a bonus, I also added the genres to the meta items (so it's visible on the right side in the Discover page), added IMDB rating and nr of votes, metascore and description.

Please test it out and reopen the issue if needed, but I think it should work fine.
