### ISSUE TITLE
no way to remove films from list

### ISSUE THREAD

**Issue by nosiedarling** [jaruba/stremio-imdb-watchlist#2]
Hi,

I've noticed there doesn't seem to be any way of removing films once they're added to the local list, even when removed from imdb web watchlist. Tried reinstalling the addon but no luck.

Thanks

**Comment by jaruba** [comment]
I think they do get removed from this addon's catalog too after you remove them on IMDB.

But the cache is set to one week:
https://github.com/jaruba/stremio-imdb-watchlist/blob/master/index.js#L36

So it will take up to one week for the changes to show in the addon too.
