### ISSUE TITLE
Getting some npm warnings and no URL from npm start

### ISSUE THREAD

**Issue by Kabouik** [jaruba/stremio-imdb-watchlist#3]
This is what I am getting when trying to follow the instructions:

```
[kabouik@kabouik-manjaro .config]$ git clone https://github.com/jaruba/stremio-imdb-watchlist.git
Cloning into 'stremio-imdb-watchlist'...
remote: Enumerating objects: 6, done.
remote: Counting objects: 100% (6/6), done.
remote: Compressing objects: 100% (6/6), done.
remote: Total 53 (delta 2), reused 0 (delta 0), pack-reused 47
Unpacking objects: 100% (53/53), 15.37 KiB | 542.00 KiB/s, done.
[kabouik@kabouik-manjaro .config]$ cd stremio-imdb-watchlist
[kabouik@kabouik-manjaro stremio-imdb-watchlist]$ npm i
npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN stremio-imdb-watchlist@0.0.1 No repository field.
npm WARN stremio-imdb-watchlist@0.0.1 No license field.

added 77 packages from 88 contributors and audited 170 packages in 3.915s
found 0 vulnerabilities

[kabouik@kabouik-manjaro stremio-imdb-watchlist]$ npm start

> stremio-imdb-watchlist@0.0.1 start /home/kabouik/.config/stremio-imdb-watchlist
> node index.js

[kabouik@kabouik-manjaro stremio-imdb-watchlist]$ 
```
This is on Manjaro and npm is up to date.

**Comment by jaruba** [comment]
There is no issue here, this addon was made to work with serverless deployments (such as now.sh), it exports a router.

If you want to test it locally, you'll need to require this as a module, create your own http server, and attach the router to it.

**Comment by Kabouik** [comment]
Oh, sorry for the noise then, I had misunderstood how to use stremio-imdb-watchlist. I thought I could use it with the base Stremio application the way I tried.

I do not have the technical knowledge to do what you suggested unfortunately, but maybe there are other tools that could allow me to synchronize both Stremio and IMDB watchlists, I'll have a look.

**Comment by jaruba** [comment]
No, it seems I was wrong actually, re-reading my readme it seems to imply that a local server will be created for testing purposes.

I've fixed it now, if you try to install it again (exactly like you did before) it will work this time.

If you just want a catalog in Stremio that syncs with a IMDB watchlist, then you don't need to install this addon locally at all, you can just use the (already deployed) remote version at:
`https://imdb-watchlist.baby-supernode.xyz/[imdb-user-id]/manifest.json`

Just change `[imdb-user-id]` with you IMDB user ID, make sure your Watchlist is set to public, and paste the addon URL (that i pasted above, after adding the IMDB user ID) in the Stremio search field and press Enter.

**Comment by Kabouik** [comment]
Awesome. It worked (although it only lists 32 movies at the moment out of more than 500, maybe it takes time to synchronize?). Thanks a lot, I had no idea it was that simple.
