### ISSUE TITLE
content did not load

### ISSUE THREAD

**Issue by sofiacif** [jaruba/stremio-imdb-watchlist#4]
Hi, 

I'm trying to use the add on but I'm getting this error

maybe I'm doing something wrong but I can't figure out what
I'm new to this so sorry if this is just a dumb question

Thank you!

<img width="1340" alt="Screenshot 2020-04-17 at 10 26 30" src="https://user-images.githubusercontent.com/18124749/79554551-1ee51200-8096-11ea-99e0-ff0db4143f32.png">

**Comment by jaruba** [comment]
yeah, i'm having some issues with the new deployment solution, i'll figure it out in the next few days

**Comment by jaruba** [comment]
I've created a new endpoint:
`https://1fe84bc728af-imdb-watchlist.beamup.dev/`
Example usage: `https://1fe84bc728af-imdb-watchlist.beamup.dev/ur1000000/manifest.json`

Tell me if it works for you.

**Comment by sofiacif** [comment]
Perfect! it works

thank you so much!
